language: python
python:
  - "2.7_with_system_site_packages"

virtualenv:
  system_site_packages: true

before_install:
  - chmod +x run_py_tests.sh
  - sudo apt-get install -y python-smbus

install:
  - pip install numpy

script:
  - ./run_py_tests.sh