language: python
python:
  - "2.7"

before_install:
  - chmod +x run_py_tests.sh
  - sudo apt-get install python-smbus -y

install:
  - pip install numpy
  - pip install smbus

script:
  - ./run_py_tests.sh